### ISSUE TITLE
Issues when downloading certain albums.

### ISSUE THREAD

**Issue by ThePlayingGoblin** [TripleFrequency/AthamePlugin.Deezer#2]
This one in particular:
http://www.deezer.com/us/album/7941240
I get this when I try to add.
https://s17.postimg.org/v1wut6k5b/log.png

I did not get this problem when I downloaded using the Tampermonkey script.

**Comment by TripleFrequency** [comment]
I have just fixed the issue. It will be in the next release in an hour or so. I am currently working on something else, and it will go with that.

**Comment by ThePlayingGoblin** [comment]
I still get this issue with certain albums after updating.
One example:
http://www.deezer.com/us/album/6851085
